#!/bin/bash
# 验证直链下载字体
echo "=== 直链下载字体 ==="
direct_fonts=(
  "https://gw.alipayobjects.com/os-download/alipay-font/AlibabaPuHuiTi-3-55-Regular.ttf|AlibabaPuHuiTi-3-Regular"
  "https://developer.huawei.com/images/202403/consumer/HarmonyOS-Sans/SC/HarmonyOS-Sans-SC-Regular.ttf|HarmonyOS-Sans-SC-Regular"
  "https://developer.huawei.com/images/202403/consumer/HarmonyOS-Sans/SC/HarmonyOS-Sans-SC-Bold.ttf|HarmonyOS-Sans-SC-Bold"
  "https://html-static.xiaomi.com/atom-fonts/MiSans/MiSans-Regular.ttf|MiSans-Regular"
  "https://html-static.xiaomi.com/atom-fonts/MiSans/MiSans-Bold.ttf|MiSans-Bold"
  "https://html-static.xiaomi.com/atom-fonts/MiSans/MiSans-Light.ttf|MiSans-Light"
  "https://html-static.xiaomi.com/atom-fonts/MiSans/MiSans-Medium.ttf|MiSans-Medium"
  "https://html-static.xiaomi.com/atom-fonts/MiSans/MiSans-Heavy.ttf|MiSans-Heavy"
  "https://html-static.xiaomi.com/atom-fonts/MiSans/MiSans-Semibold.ttf|MiSans-Semibold"
  "https://html-static.xiaomi.com/atom-fonts/MiSans/MiSans-Demibold.ttf|MiSans-Demibold"
  "https://html-static.xiaomi.com/atom-fonts/MiSans/MiSans-Thin.ttf|MiSans-Thin"
  "https://html-static.xiaomi.com/atom-fonts/MiSans/MiSans-UltraLight.ttf|MiSans-UltraLight"
  "https://html-static.xiaomi.com/atom-fonts/HarmonyOS-Sans/HarmonyOS-Sans-Regular.ttf|HarmonyOS-Sans-Regular"
)

for entry in "${direct_fonts[@]}"; do
  url="${entry%%|*}"
  name="${entry##*|}"
  status=$(curl -sI -A "Mozilla/5.0" "$url" | head -1 | awk '{print $2}')
  echo "$name: $status ($url)"
done

echo "=== cdnfonts 第二轮 ==="
# 更多 cdnfonts 字体
more_cdnfonts=(
  "Smiley%20Sans%20WenQuanYi"
  "MiSansVF"
  "Noto%20Sans%20Mono"
  "Sarasa%20Gothic%20SC"
  "Sarasa%20Mono%20SC"
  "TW%20Kai"
  "Fake%20Pearl"
  "AoyagiKouzanFont2"
  "Klee%20One"
  "Train%20One"
  "Stick"
  "RocknRoll%20One"
  "Reggae%20One"
  "Rampart%20One"
  "DotGothic16"
  "Yusei%20Magic"
  "Zen%20Maru%20Gothic"
  "Zen%20Kaku%20Gothic%20New"
  "Zen%20Kurenaido"
  "Zen%20Old%20Mincho"
  "Zen%20Antique"
  "Zen%20Antique%20Soft"
  "Hachi%20Maru%20Pop"
  "Kaisei%20Decol"
  "Kaisei%20Opti"
  "Kaisei%20Tokumin"
  "Klee%20One%20Pro"
  "Klee%20One"
  "Klee%20One%20SemiBold"
  "Zen%20Maru%20Gothic%20New"
  "Mochiy%20Pop%20One"
  "Mochiy%20Popp%20One"
  "Dela%20Gothic%20One"
  "Hina%20Mincho"
  "Kaisei%20HarunoUmi"
  "Kaisei%20Hunmin"
  "Kaisei%20Reiwa"
  "Kaisei%20Torture"
  "Rampart%20One"
  "Rock%20n%20Roll%20One"
  "Reggae%20One"
  "Stick"
  "Train%20One"
  "DotGothic16"
  "New%20Tegomin"
  "Shippori%20Mincho"
  "Shippori%20Mincho%20B1"
  "Sawarabi%20Gothic"
  "Sawarabi%20Mincho"
  "Yomogi"
  "Zen%20Maru%20Gothic"
  "Zen%20Kaku%20Gothic%20Antique"
  "Zen%20Kaku%20Gothic%20New"
  "Zen%20Kurenaido"
  "Zen%20Old%20Mincho"
  "Zen%20Antique"
  "Zen%20Antique%20Soft"
  "Klee%20One"
  "Klee%20One%20Pro"
  "Dela%20Gothic%20One"
  "Hachi%20Maru%20Pop"
  "Mochiy%20Pop%20One"
  "Mochiy%20Popp%20One"
  "Hina%20Mincho"
  "Yusei%20Magic"
  "Kaisei%20Decol"
  "Kaisei%20HarunoUmi"
  "Kaisei%20Hunmin"
  "Kaisei%20Opti"
  "Kaisei%20Reiwa"
  "Kaisei%20Tokumin"
  "Kaisei%20Torture"
  "Kaisei%20Bunntoun"
)

for f in "${more_cdnfonts[@]}"; do
  url="https://fonts.cdnfonts.com/css?family=${f}"
  status=$(curl -sI -A "Mozilla/5.0" "$url" | head -1 | awk '{print $2}')
  echo "$f: $status"
done
